# ISA Standard Compliant
# Distributed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0
services:
  mongo:
    image: mongo:7
    container_name: talk-to-data-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
